name: Release
on:
  push:
    tags:
      - v*-d2iq.*

# Because variables are not exported, they are not visible by child processes, e.g. make
env:
  version: ${{ github.ref_name }}
  registry: ghcr.io
  # The repository follows the naming convention of other Cluster API providers.
  repository: mesosphere/cluster-api-vcd-controller

jobs:
  release:
    name: Release
    runs-on:
      - self-hosted
      - small
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true # cache go action in github actions cache store.
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate container image
        run: |
          make generate-capvcd-image \
            REGISTRY=${{ env.registry }} \
            CAPVCD_IMG=${{ env.repository }} \
            VERSION=${{ env.version }}
      - name: Push container image to container registry
        run: |
          make push-capvcd-image \
            REGISTRY=${{ env.registry }} \
            CAPVCD_IMG=${{ env.repository }} \
            VERSION=${{ env.version }}
